# Generated by Django 5.2.17 on 2026-10-04 10:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_likers_post_comments_count_post_lovers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',), 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'دسته بندی های مقاله'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('post',), 'verbose_name_plural': 'کامنت های مقاله'},
        ),
        migrations.AlterModelOptions(
            name='postseen',
            options={'ordering': ('post',), 'verbose_name_plural': 'بازدید های مقاله'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_authors', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.postcategory', verbose_name='دسته بندی مقاله'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کامنت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lovers',
            field=models.ManyToManyField(related_name='post_lovers', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده ها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/category', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='haters',
            field=models.ManyToManyField(related_name='post_comment_haters', to=settings.AUTH_USER_MODEL, verbose_name='هیت دهنده ها'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='جواب کامنت'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='lovers',
            field=models.ManyToManyField(related_name='post_comment_lovers', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده ها'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcomment', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='postseen',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آیپی آدرس'),
        ),
        migrations.AlterField(
            model_name='postseen',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_seen', to='posts.post', verbose_name='مقاله'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='مقاله',
        ),
        migrations.AlterModelTable(
            name='postcategory',
            table='دسته بندی مقاله',
        ),
        migrations.AlterModelTable(
            name='postcomment',
            table='کامنت مقاله',
        ),
        migrations.AlterModelTable(
            name='postseen',
            table='بازدید مقاله',
        ),
    ]
