# Generated by Django 5.2.17 on 2026-09-01 11:02

import accounts.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ('phone_number',), 'verbose_name_plural': 'otpcodes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('phone_number',), 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveIntegerField(unique=True, validators=[accounts.model_field_validation.otp_code_validation]),
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table='otpcode',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
