# Generated by Django 5.2.17 on 2026-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
