# Generated by Django 5.2.17 on 2026-10-04 08:33

import accounts.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ('phone_number',), 'verbose_name_plural': 'کدهای یکبار مصرف'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('phone_number',), 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveIntegerField(unique=True, validators=[accounts.model_field_validation.otp_code_validation], verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شاره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='سوپر ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='فامیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='کد پستی'),
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table='کد یکبار مصرف',
        ),
        migrations.AlterModelTable(
            name='user',
            table='کاربر',
        ),
    ]
