# Generated by Django 5.2.17 on 2026-09-16 10:32

import django_jalali.db.models
import products.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation])),
                ('available', models.BooleanField(default=False)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('start_date', django_jalali.db.models.jDateTimeField()),
                ('end_date', django_jalali.db.models.jDateTimeField()),
            ],
            options={
                'verbose_name_plural': 'coupons',
                'db_table': 'coupon',
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',), 'verbose_name_plural': 'order_items'},
        ),
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.PositiveIntegerField(default=0, validators=[products.model_field_validation.price_validation]),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation]),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_price',
            field=models.PositiveIntegerField(default=0, validators=[products.model_field_validation.price_validation]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
