# Generated by Django 5.2.17 on 2026-09-16 11:27

import products.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation]),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation]),
        ),
    ]
