# Generated by Django 5.2.17 on 2026-09-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
