# Generated by Django 5.2.17 on 2026-09-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_created_at_coupon_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ('coupon',), 'verbose_name_plural': 'coupon_usages'},
        ),
    ]
