# Generated by Django 5.2.17 on 2026-10-04 10:26

import django.db.models.deletion
import django_jalali.db.models
import products.model_field_validation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_order'),
        ('products', '0040_alter_brand_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('code',), 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ('coupon',), 'verbose_name_plural': 'استفاده های کد نخفیف'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',), 'verbose_name_plural': 'آیتم های سفارش'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='available',
            field=models.BooleanField(default=False, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='حداکثر استفاده'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='base_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation], verbose_name='قیمت اولیه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='فامیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation], verbose_name='قیمت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=255, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[products.model_field_validation.price_validation], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.variant', verbose_name='متغیر'),
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='کد تخفیف',
        ),
        migrations.AlterModelTable(
            name='couponusage',
            table='استفاده کد تخفیف',
        ),
        migrations.AlterModelTable(
            name='order',
            table='سفارش',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='آیتم سفارش',
        ),
    ]
