# Generated by Django 5.2.17 on 2026-09-05 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_parent_alter_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='product_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
