# Generated by Django 5.2.17 on 2026-09-05 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment_dislikes_comment_likers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
