# Generated by Django 5.2.17 on 2026-09-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_comment_dislikes_comment_dislikers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_change', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'price_changes',
                'db_table': 'price_change',
                'ordering': ('product',),
            },
        ),
    ]
