# Generated by Django 5.2.17 on 2026-09-07 09:46

import django.db.models.deletion
import products.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pricechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('hex_code', models.CharField(max_length=100, unique=True)),
                ('extra_price', models.PositiveIntegerField(default=0, validators=[products.model_field_validation.price_validation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'colors',
                'db_table': 'color',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('extra_price', models.PositiveIntegerField(default=0, validators=[products.model_field_validation.price_validation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'sizes',
                'db_table': 'size',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('unit_price', models.PositiveIntegerField(default=0, validators=[products.model_field_validation.price_validation])),
                ('discount', models.PositiveIntegerField(default=0, validators=[products.model_field_validation.discount_validation])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size')),
            ],
            options={
                'verbose_name_plural': 'variants',
                'db_table': 'variant',
                'ordering': ('name',),
            },
        ),
    ]
