# Generated by Django 5.2.17 on 2026-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_color_size_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
