# Generated by Django 5.2.17 on 2026-09-08 09:54

import products.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_color_extra_price_alter_size_extra_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[products.model_field_validation.discount_validation]),
        ),
    ]
