# Generated by Django 5.2.17 on 2026-09-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='unit_price',
        ),
    ]
