# Generated by Django 5.2.17 on 2026-09-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_variant_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
