# Generated by Django 5.2.17 on 2026-09-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variant_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='start_price',
        ),
    ]
