# Generated by Django 5.2.17 on 2026-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_base_price_product_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
