# Generated by Django 5.2.17 on 2026-09-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_variant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
