# Generated by Django 5.2.17 on 2026-09-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechange',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='products.variant'),
        ),
    ]
