# Generated by Django 5.2.17 on 2026-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_pricechange_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ('variant',), 'verbose_name_plural': 'price_changes'},
        ),
        migrations.RemoveField(
            model_name='pricechange',
            name='product',
        ),
    ]
