# Generated by Django 5.2.17 on 2026-09-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_pricechange_options_remove_pricechange_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
