# Generated by Django 5.2.17 on 2026-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechange',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
