# Generated by Django 5.2.17 on 2026-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_pricechange_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
