# Generated by Django 5.2.17 on 2026-09-16 10:32

import products.model_field_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_comment_updated_at_pricechange_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation]),
        ),
    ]
