# Generated by Django 5.2.17 on 2026-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'price_changes'},
        ),
    ]
