# Generated by Django 5.2.17 on 2026-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_pricechange_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'price_changes'},
        ),
    ]
