# Generated by Django 5.2.17 on 2026-09-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_extraimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimage',
            old_name='alt_text',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='extraimage',
            old_name='caption',
            new_name='title',
        ),
    ]
