# Generated by Django 5.2.17 on 2026-09-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_alt_text_extraimage_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimage',
            old_name='alt',
            new_name='alt2',
        ),
        migrations.RenameField(
            model_name='extraimage',
            old_name='title',
            new_name='title3',
        ),
    ]
