# Generated by Django 5.2.17 on 2026-09-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_rename_alt_extraimage_alt2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimage',
            old_name='alt2',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='extraimage',
            old_name='title3',
            new_name='title',
        ),
    ]
