# Generated by Django 5.2.17 on 2026-09-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_alt2_extraimage_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimage',
            old_name='title',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='extraimage',
            old_name='alt',
            new_name='image_title',
        ),
    ]
