# Generated by Django 5.2.17 on 2026-09-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_rename_title_extraimage_image_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimage',
            old_name='image_alt',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='extraimage',
            old_name='image_title',
            new_name='title',
        ),
    ]
