# Generated by Django 5.2.17 on 2026-09-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_rename_image_alt_extraimage_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seen', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'product_sees',
                'db_table': 'product_seen',
                'ordering': ('product',),
            },
        ),
    ]
