# Generated by Django 5.2.17 on 2026-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_rename_total_seen_product_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
    ]
