# Generated by Django 5.2.17 on 2026-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
