# Generated by Django 5.2.17 on 2026-10-04 10:26

import ckeditor_uploader.fields
import django.db.models.deletion
import products.model_field_validation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_contactus_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'دسته بندی های محصول'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('name',), 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('product',), 'verbose_name_plural': 'کامنت های محصول'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'ارتباط با ما'},
        ),
        migrations.AlterModelOptions(
            name='extraimage',
            options={'ordering': ('product',), 'verbose_name_plural': 'تصویر های اضافه'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name_plural': 'جنس ها'},
        ),
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'تغییر های قیمت'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='productseen',
            options={'ordering': ('product',), 'verbose_name_plural': 'بازدید های محصول'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('name',), 'verbose_name_plural': 'سایز ها'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('name',), 'verbose_name_plural': 'متغیر ها'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='داشتن پدر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='extra_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت اضافه'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد هگز رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikers', to=settings.AUTH_USER_MODEL, verbose_name='هیت دهنده ها'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='comment_likers', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده ها'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.comment', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='done',
            field=models.BooleanField(default=False, verbose_name='اتمام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگرین'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(upload_to='product_extra_images/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='products.variant', verbose_name='متغیر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته بندی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='داشتن تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='product_likers', to=settings.AUTH_USER_MODEL, verbose_name='لایک کننده ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.material', verbose_name='جنس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_price',
            field=models.PositiveIntegerField(validators=[products.model_field_validation.price_validation], verbose_name='قیمت اولیه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='productseen',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آیپی آدرس'),
        ),
        migrations.AlterField(
            model_name='productseen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seen', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='size',
            name='extra_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت اضافه'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[products.model_field_validation.discount_validation], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت هر واحد'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='برند',
        ),
        migrations.AlterModelTable(
            name='category',
            table='دسته بندی محصول',
        ),
        migrations.AlterModelTable(
            name='color',
            table='رنگ',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='کامنت محصول',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='ارتباط با ما',
        ),
        migrations.AlterModelTable(
            name='extraimage',
            table='تصویر اضافه',
        ),
        migrations.AlterModelTable(
            name='material',
            table='جنس',
        ),
        migrations.AlterModelTable(
            name='pricechange',
            table='تغییر قیمت',
        ),
        migrations.AlterModelTable(
            name='product',
            table='محصول',
        ),
        migrations.AlterModelTable(
            name='productseen',
            table='بازدید محصول',
        ),
        migrations.AlterModelTable(
            name='size',
            table='سایز',
        ),
        migrations.AlterModelTable(
            name='variant',
            table='متغیر',
        ),
    ]
