# Generated by Django 5.2.17 on 2026-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='done',
            field=models.BooleanField(default=False, verbose_name='بررسی شد'),
        ),
    ]
